### ISSUE TITLE
BLEAK installation issue

### ISSUE THREAD

**Issue by ysc1** [plasma-umass/BLeak#38] opened 2019-01-07 14:54 UTC
Hello BLEAK Team,

When we are trying to install BLEAK Using GIT BASH withcommand: "npm install -g bleak-detector" we are getting below error log:

$ npm install -g bleak-detector
C:\Users\ysc1\AppData\Roaming\npm\bleak -> C:\Users\ysc1\AppData\Roaming\npm\node_modules\bleak-detector\dist\node\cli\bleak.js

> bufferutil@3.0.5 install C:\Users\ysc1\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

> utf-8-validate@4.0.2 install C:\Users\ysc1\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\utf-8-validate
> prebuild-install || node-gyp rebuild

> mitmproxy@2.1.0 postinstall C:\Users\ysc1\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\mitmproxy
> scripts/install_python_deps.py

'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mitmproxy@2.1.0 postinstall: `scripts/install_python_deps.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mitmproxy@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ysc1\AppData\Roaming\npm-cache\_logs\2019-01-07T14_52_05_753Z-debug.log

FYI:
We have all the valid versions of MITPROXY, PYTHON, VISUAL STUDIO and all required Softwares.

Python: 3.7.1 Version
MITPROXY: 4.0.1
Visula Studio: 2017

It would be great if you can guide us with some workaround or solution if you have found any.

**Comment by jvilk** [comment] 2019-05-02 05:41
It looks like there's an issue installing the package on Windows. It works fine on my Mac.

I'll see if I can get this working cross-platform.

**Comment by jvilk** [comment] 2019-05-02 05:47
I'm closing this issue as it's a duplicate of https://github.com/plasma-umass/BLeak/issues/35

**Closed by jvilk** 2019-05-02 05:47 UTC

**Comment by jvilk** [comment] 2019-05-02 06:18
I just released v1.2.2, which should fix this problem.
