### ISSUE TITLE
JS crash on final run of BLeak

### ISSUE THREAD

**Issue by msridhar** [plasma-umass/BLeak#25] opened 2018-03-30 22:24 UTC
This might be related to #14 but I'm not sure.  I tried BLeak on a site, and it seemed to get through the first phase of loading the site in a loop and collecting heap snapshots.  But at the "Diagnosing leaks" phase (where I think it does JS instrumentation) the site doesn't load and I get a JS error `Uncaught TypeError: Cannot read property 'defineProperty' of undefined`.  Unfortunately this is not a public site so I can't share code / repro steps.  Two questions:
1. Short of sharing source code, is there any other info I could share to help narrow down the problem?
2. Is it possible to run BLeak without the final diagnosis phase and still get some information about the detected leaks?  Or is the output pretty useless without the final diagnosis info?

Regarding #14, I do *not* see any `bleak_results.json` in my output directory at the point the JS error appears.

**Comment by jvilk** [comment] 2018-03-30 22:58
This sounds like a bug in JavaScript instrumentation, as you say.

If this issue happens *immediately* during leak diagnosis, you can run a proxy session with instrumentation on, and then use Chrome's dev tools to investigate the error:

```
bleak proxy-session --config [path_to_config_file] --diagnose
```

Note that the `master` branch in Git has some JavaScript rewriting fixes that have not been pushed to NPM yet. I'm waiting until after artifact evaluation to cut a new release. If you're using the NPM release, can you try the `master` version? (After building, there's a `bleak` shell script in the repo root that runs the built version.)

You're right about #14; I believe I removed the saving logic when I refactored BLeak prior to artifact evaluation. I just restored it in a commit and hand-tested it; it writes `bleak_results.json` and `bleak_report.log` after finding leaks, and automatically resumes from them if you run BLeak with config directory that contains them. You should be able to run BLeak and see what leak roots are growing.

**Comment by jvilk** [comment] 2018-03-30 23:08
Regarding info you could provide to me, it's challenging to help fix without seeing the source code / transformed code side-by-side. If the transformed code immediately looks incorrect, or raises a specific suspicion as to the cause of the error, you could golf it down to a minimal test case that you can share.

The easiest way to test a golfed-down test case is to edit and reload a simple `index.html` during a proxy-session with the `--diagnose` flag enabled until you find the way to trigger the failure.

**Comment by msridhar** [comment] 2018-03-30 23:14
Thanks! I'll give the master version a try and see how that goes.

**Comment by msridhar** [comment] 2018-03-30 23:37
Looks like things are still broken on master.  I will see if I can track down the problem enough to submit a repro case.

On the plus side, I am seeing the leak report output now.  And it made me realize that having the diagnosis output would be extremely useful 😄

**Comment by jvilk** [comment] 2018-03-30 23:59
Thanks in advance for looking into this, and good luck! Let me know if you have any questions about the code transformation.

The code transformation should just move all local variables that escape into closures into scope objects, and then assign those scope objects to function objects. It might pass your code through a transpiler first -- Buble or Babel -- if you use anything beyond ES5 features (it tries Buble first, and falls back to the very slow Babel if the code uses a feature Buble cannot support). The transpilation occurs during leak detection as well, so that is obviously not causing the problem, but it may make it more challenging to do a side-by-side with the original code! 

There are some subtleties to the approach if you use `with` or `eval`. Arguments are also handled specially to make sure they still alias to the `arguments` object appropriately. One thing I did not implement is `Function(string)` and `setTimeout(string)`, which evaluate code in the global context, so if you use those constructs in your code and they seem to be an issue, let me know and I'll see about hacking in support!

There's also a `bleak transform-javascript` command that you might find handy. Using this command, you can run the ES5ification pass and the diagnosis pass on a file (see the `--help` text for info).

**Comment by msridhar** [comment] 2018-03-31 00:25
Ok, here's an excerpt of instrumented code:
```javascript
function runInContext(context, exports) {
	var s91 = $$$CREATE_SCOPE_OBJECT$$$(s90, ["Number", "String", "Date", "SyntaxError", "TypeError", "getClass", "isProperty", "forEach", "undef", "isExtended", "functionClass", "dateClass", "numberClass", "stringClass", "arrayClass", "booleanClass", "charIndexBuggy", "floor", "Months", "getDay", "Escapes", "leadingZeroes", "toPaddedString", "unicodePrefix", "quote", "serialize", "fromCharCode", "Unescapes", "Index", "Source", "abort", "lex", "get", "update", "walk"], {
		has: {
			get: function () {
				return has;
			},
			set: function (v) {
				has = v;
			}
		}
	}, ["exports"], [exports]);
        // CRASH HERE
	Object.defineProperty(has, '__scope__', {
		get: function () {
			return s91;
		},
		configurable: true
	});
	context || (context = s90.root["Object"]());
	s91.exports || (s91.exports = s90.root["Object"]());
	s91.Number = context["Number"] || s90.root["Number"];
	s91.String = context["String"] || s90.root["String"];
	var Object = context["Object"] || s90.root["Object"];
	...
```
Just looking at this code I think I can see the cause of the crash.  The declaration of the `Object` local variable gets hoisted, so at the point of the `Object.defineProperty()` call it is still `undefined` as it hasn't been assigned yet.  No idea why this happens, but maybe it's enough to debug the problem.

**Comment by jvilk** [comment] 2018-03-31 00:53
Ah! That completely makes sense; BLeak naively assumed that `Object` always refers to the global `window.Object`, so if there's a local variable, things go off track.

I'll see about putting together a quick fix...

**Comment by jvilk** [comment] 2018-03-31 01:15
Added a quick hack fix and a unit test. BLeak now defines the global variable `$$$OBJECT$$$` that it refers to instead of `Object`. It doesn't solve the root of the problem, but it's good enough to fix what you are experiencing.

I opened up #27 to develop a more permanent fix, since BLeak introduces many global variables (purely for convenience).

**Comment by msridhar** [comment] 2018-03-31 02:27
Thanks for the quick fix!!  Will try soon.

**Comment by msridhar** [comment] 2018-03-31 15:48
Confirmed that I get past the crash now.  Something doesn't seem to work quite properly a bit later, but that'll take more time to diagnose, and I won't have time for a while.  Thanks for fixing this one!

**Comment by jvilk** [comment] 2018-03-31 17:48
Aw, that's too bad. Note that if BLeak reaches 100% and errors, then it might have actually completed successfully. There are two errors that are safe to ignore.

Error 1:
```
Error in data transfer
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/websockets/protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/websockets/protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/websockets/protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/websockets/protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/opt/python/3.6.3/lib/python3.6/asyncio/streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/opt/python/3.6.3/lib/python3.6/asyncio/streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/websockets/protocol.py", line 669, in write_frame
    yield from self.writer.drain()
  File "/opt/python/3.6.3/lib/python3.6/asyncio/streams.py", line 323, in drain
    raise exc
  File "/opt/python/3.6.3/lib/python3.6/asyncio/selector_events.py", line 762, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

Error 2:
```
(node:5259) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: socket disconnect
(node:5259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

These are caused by race conditions in BLeak's shutdown code between BLeak, Chrome, and the BLeak proxy, which all run as separate processes. The errors occur deep in third-party dependencies, so I haven't figured out an easy way to suppress them yet.

**Comment by msridhar** [comment] 2018-03-31 18:14
This issue wasn't one of those; one of the clicks on the site wasn't working (or was working very slowly) after running with BLeak diagnosis instrumentation.  I can probably figure it out, but like I said won't have time to dig for a bit.  BLeak did seem to succeed in the end with a bit of stack output, which was useful.  I didn't write the code on this site and it uses some frameworks I don't understand.  But if/when I get back to this and speak to one of the devs, I'll report back on how actionable the errors were.

Thanks again!  Great support!

**Comment by jvilk** [comment] 2018-08-11 17:15
I'll close this for now. Please let me know if there's any additional information that you can share regarding the click problem, or if you have any other issues with BLeak!

**Closed by jvilk** 2018-08-11 17:15 UTC
Labels: bug
